modLoader = "javafml"
loaderVersion = "*"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "croparia_dynamics"
version = "${version}"
displayName = "Croparia IF: Dynamics"
authors = "MUYU_Twilighter"
description = '''
Bring automation to Croparia IF
'''
#logoFile = ""

[[dependencies.croparia_dynamics]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.croparia_dynamics]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.croparia_dynamics]]
modId = "architectury"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
